### ISSUE TITLE
Add more arguments to select input files

### ISSUE THREAD

**Issue by ghost** [pepamengual/NetCleave#1]
Hi! 
I'm running multiple predictions and I had to edit the code to use different input files by changing  the hardcoded path of the example. 
It would be nice to update NetCLeave.py and allow to custom the path and MHC type with arguments. This will allow to automatize workflows.
Best

**Comment by pepamengual** [comment]
Hello,

The current version of NetCleave should work now. In this update, one can run NetCleave by using python commands/using a bash script. Let me know if that works for you

Best,
Pep

**Comment by RexTremendae1** [comment]
Hello, 
This update is really useful. 
Thanks
